name: WorldGuardGriefFix
version: '${project.version}'
main: ru.overwrite.wggf.WorldGuardGriefFixPlugin
api-version: 1.13
authors: [ Overwrite, Afek ]

commands:
  wggf:
    aliases: [ worldguardgrieffix ]
